{{- range $name, $values := .Values.Servers }}
{{- if $values.ingress.enabled -}}
{{- $fullName := include "<CHARTNAME>.fullname" $ -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "<CHARTNAME>.fullname" $ }}-{{ $name }}
  labels:
    app: {{ include "<CHARTNAME>.name" $ }}
    chart: {{ include "<CHARTNAME>.chart" $ }}
    release: {{ $.Release.Name }}
    helm.sh/chart: {{ include "<CHARTNAME>.chart" $ }}
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
  {{- with $values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $host := $values.ingress.hosts }}
  {{- if $host.subdomain.enabled }}
    {{- $subdomain := default $fullName $host.subdomain.value }}
    - host: {{ printf "%s.%s" $subdomain $host.zone | quote }}
  {{- else }}
    - host: {{ tpl $host.zone $ | quote }}
      http:
        paths:
          - path: {{ $values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-{{ $name }}
                port:
                  number: 80
  {{- end }}
  {{- if $values.ingress.tls }}
  tls:
  - hosts:
    - {{ tpl $host.zone $ | quote }}
    secretName: {{ tpl $values.ingress.tls.secretName $ | quote}}
  {{- end}}
  {{- end }}
{{- end }}
{{- end }}