{{- range $name, $values := .Values.Servers }}
{{- if  $values.environmentVariablesOnePasswordPath }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "<CHARTNAME>.fullname" $ }}-{{ $name }}-environment-variables
spec:
  itemPath: {{ $values.environmentVariablesOnePasswordPath }}
{{- end }}
{{- end }}